# Generated by Django 3.0.4 on 2020-05-03 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200502_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_corectly1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_corectly2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_corectly3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_corectly4',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
