# Generated by Django 3.0.4 on 2020-05-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200503_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_question',
        ),
    ]
